name: Setup  ESS Kind Cluster
description: Setup ESS Kind Cluster
inputs:
  containerd-mirrors-path:
    description: "Containerd mirrors path."
    required: false
  kind-shared-mount-path:
    description: "Kind shared mount path."
    required: false
    default: "."
  cert-manager-version:
    description: "Cert manager version."
    required: false
    default: "1.19.0"
  ingress-nginx-version:
    description: "Ingress nginx version."
    required: false
    default: "4.13.3"
  metrics-server-version:
    description: "Metrics server version."
    required: false
    default: "3.13.0"
  prometheus-operator-version:
    description: "Prometheus operator version."
    required: false
    default: "9.3.2"
  kind-version:
    description: "Kind version."
    required: false
    default: "v0.30.0"
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a  # v7.4.0
      with:
        enable-cache: true
        activate-environment: true
        python-version: "3.14"

    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4  # v4.3.1

    - name: Install ess-helm pytest packege
      shell: bash
      run: |
        uv init || echo "Already initialized"
        uv add git+https://github.com/element-hq/ess-helm.git@gaelg/pytest-test-package#subdirectory=tests

    - name: Install ess-helm pytest packege
      shell: bash
      run: |
        PYTEST_KEEP_CLUSTER=1 pytest --pyargs ess-community-integration-tests --env-setup

        k3d kubeconfig merge ess-helm -ds

    - name: Create action workdir
      shell: bash
      run: |
        mkdir -p .setup-ess-cluster-action

    - name: Setup runner paths
      shell: bash
      id: setup-paths
      env:
        SHARED_MOUNT_PATH: "${{ inputs.shared-mount-path }}"
        CONTAINERD_MIRRORS_PATH: "${{ inputs.containerd-mirrors-path }}"
      run: |
        if [[ "$ELEMENT_DIND_RUNNER" == "true" ]]; then
          echo "Enabling private mirrors"
          echo "shared-mount-path=/dind-job-shared" | tee -a $GITHUB_OUTPUT
          echo "containerd-mirrors-path=/containerd-pull-through-cache" | tee -a $GITHUB_OUTPUT
        else
          echo "kind-shared-mount-path=$SHARED_MOUNT_PATH" | tee -a $GITHUB_OUTPUT
          echo "containerd-mirrors-path=$CONTAINERD_MIRRORS_PATH" | tee -a $GITHUB_OUTPUT
        fi

    - name: Export logs
      if: ${{ failure() }}
      shell: bash
      run: |
        kind export logs --name ess-helm ./ess-helm-cluster-logs

    - name: Upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
      with:
        name: ess-helm-cluster-logs
        path: ess-helm-cluster-logs
        retention-days: 1