name: Setup ESS Cluster
description: Setup ESS Cluster
inputs:
  ess-helm-ref:
    description: The ref of the tag or branch to use to install ess-community-integration-tests
    required: true
    default: "main"
  ess-repository:
    description: The repository to install ess-community-integration-tests from
    default: "https://github.com/element-hq/ess-helm.git"
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a  # v7.4.0
      with:
        enable-cache: true
        activate-environment: true
        python-version: "3.14"

    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4  # v4.3.1

    - name: Get current week number and home dir
      id: cache-input
      shell: bash
      run: |
        echo "week=$(date +%Y%U)" | tee -a "$GITHUB_OUTPUT"
        echo "runner-home=$HOME" | tee -a "$GITHUB_OUTPUT"

    - name: Cache ASDF for a week
      id: asdf-cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306  # v5.0.3
      env:
        gh_cache_prefix: ${{ runner.os }}-${{ runner.arch }}-asdf-
      with:
        key: ${{ env.gh_cache_prefix }}week-${{ steps.cache-input.outputs.week }}
        path: |
          ${{ steps.cache-input.outputs.runner-home }}/.asdf/bin

    - name: Restore pyhelm cache
      id: cache-pyhelm
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306  # v5.0.3
      with:
        path: .pyhelm_cache
        key: pyhelm-integration-cache-week-${{ steps.cache-input.outputs.week }}
        restore-keys: |
          pyhelm-integration-cache-

    - name: List pyhelm cache contents
      shell: bash
      run: |
        echo "Listing contents of .pyhelm_cache:"
        ls -la .pyhelm_cache || echo "Cache directory does not exist or is empty"

    - name: set up ASDF
      uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47  # v4.0.1
      with:
        skip_install: ${{ steps.asdf-cache.outputs.cache-hit == 'true' }}

    - name: Write asdf .tool-versions
      id: write-asdf-tools
      env:
        ASDF_TOOLS: "k3d 5.8.3"
      shell: bash
      run: |
        echo "$ASDF_TOOLS" | tee -a ".tool-versions"
        echo "tools-hash=$(sha256sum ".tool-versions" | cut -d ' ' -f 1)" | tee -a "$GITHUB_OUTPUT"

    - name: Restore ASDF tools from cache
      id: asdf-tools-cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306  # v5.0.3
      env:
        gh_cache_prefix: ${{ runner.os }}-${{ runner.arch }}-asdf-tools-
      with:
        key: ${{ env.gh_cache_prefix }}${{ steps.write-asdf-tools.outputs.tools-hash }}
        path: |
          ${{ env.ASDF_DIR }}/plugins
          ${{ env.ASDF_DIR }}/installs

    - name: Install ASDF tools
      uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47  # v4.0.1

    - name: Lock .tool-versions globally
      shell: bash
      run: |
        cp .tool-versions "$HOME/.tool-versions"

    - name: Reshim installed ASDF tools
      shell: bash
      run: asdf reshim

    - name: Install ess-helm pytest packege
      shell: bash
      env:
        REMOTE_REF: ${{ inputs.ess-helm-ref }}
        REPOSITORY: ${{ inputs.ess-repository }}
      run: |
        uv tool install git+${REPOSITORY}@${REMOTE_REF}#subdirectory=tests

    - name: Install ess-helm pytest package
      shell: bash
      run: |
        uv run setup-ess-cluster

        k3d kubeconfig merge ess-helm -ds

    - name: Export logs
      if: ${{ failure() }}
      shell: bash
      run: |
        mkdir ess-helm-logs
        k3d kubeconfig merge ess-helm -ds
        for ns in $(kubectl --context k3d-ess-helm get ns -o custom-columns=NS:.metadata.name --no-headers); do
          mkdir -p "./ess-helm-logs/$ns"
          for pod in $(kubectl --context k3d-ess-helm -n "$ns" get pod -o custom-columns=NS:.metadata.name --no-headers); do
            kubectl --context k3d-ess-helm -n "$ns" logs --all-containers --prefix --timestamps --ignore-errors --previous "$pod" > "./ess-helm-logs/$ns/$pod.previous"
            kubectl --context k3d-ess-helm -n "$ns" logs --all-containers --prefix --timestamps --ignore-errors "$pod" > "./ess-helm-logs/$ns/$pod.logs"
          done
          resources=("pods" "deployments" "statefulsets" "services" "configmaps" "ingresses" "persistentvolumes" "persistentvolumeclaims" "endpoints")
          for i in "${resources[@]}"; do
            kubectl --context k3d-ess-helm get "$i" -n "$ns" > "./ess-helm-logs/$ns/$i.txt"
            echo "----" >> "./ess-helm-logs/$ns/$i.txt"
            kubectl --context k3d-ess-helm get "$i" -o yaml -n "$ns" >> "./ess-helm-logs/$ns/$i.txt"
          done
          kubectl --context k3d-ess-helm get events --sort-by=.metadata.creationTimestamp -n "$ns" > "./ess-helm-logs/$ns/events.txt"
          kubectl --context k3d-ess-helm get secrets -n "$ns" > "./ess-helm-logs/$ns/secrets.txt"
          echo "----" >> "./ess-helm-logs/$ns/secrets.txt"
          kubectl --context k3d-ess-helm get secrets  -o yaml -n "$ns" | yq eval '.items[].data |= with_entries(.value = "censored") | .items[].stringData |= with_entries(.value = "censored")' > "./ess-helm-logs/$ns/secrets.txt"
        done
        kubectl --context k3d-ess-helm get crds > "./ess-helm-logs/crds.txt"
          echo "----" >> "./ess-helm-logs/$ns/crds.txt"
        kubectl --context k3d-ess-helm get crds -o yaml  | yq 'del .items[].spec' > "./ess-helm-logs/crds.txt"
        docker logs k3d-ess-helm-server-0 > "./ess-helm-logs/k3d-ess-helm-server-0.logs" 2>&1
        k3d cluster delete ess-helm

    - name: Upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
      with:
        name: ess-helm-logs-${{ matrix.test-component }}-${{ matrix.test-from-ref }}
        path: ess-helm-logs
        retention-days: 1
