name: Setup ESS Cluster
description: Setup ESS Cluster
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a  # v7.4.0
      with:
        enable-cache: true
        activate-environment: true
        python-version: "3.14"

    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4  # v4.3.1

    - uses: ./.github/actions/asdf-cache
      with:
        tool-versions: |
          k3d 5.8.3

    - name: Install ess-helm pytest packege
      shell: bash
      run: |
        uv tool install git+https://github.com/element-hq/ess-helm.git@gaelg/pytest-test-package#subdirectory=tests

    - name: Install ess-helm pytest package
      shell: bash
      run: |
        uv run setup-cluster

        k3d kubeconfig merge ess-helm -ds

    - name: Export logs
      if: ${{ failure() }}
      shell: bash
      run: |
        kind export logs --name ess-helm ./ess-helm-cluster-logs

    - name: Upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
      with:
        name: ess-helm-cluster-logs
        path: ess-helm-cluster-logs
        retention-days: 1